/**
 * Spanish words that are not in the data.
 *
 * `emojilib` brings 15412 keywords in English and there is no Spanish edition:
 * "book" finds a book and "libro" finds nothing. This table closes the gap for
 * the words of this app.
 *
 * It is curated and not a dictionary, but "short on purpose" turned out to be
 * wrong as stated: measured once, 126 of 160 everyday words ("papel", "mano",
 * "puerta"...) returned nothing, so the table was not a shortcut but a hole.
 * Every entry below was checked against the real data — English word exists AND
 * returns the right emoji, because substring matching bites both ways (`bus`
 * finds businessmen through "business", `liver` finds trucks through
 * "delivery"). `test/emoji-search.test.ts` asserts every single key resolves,
 * so a dead alias fails loudly instead of rotting silently.
 *
 * The key is what the person types on a Spanish keyboard, and the value is what
 * the data brings. A key that is already English needs no alias and gets none.
 */
export const EMOJI_ALIASES: Record<string, string> = {
  libro: "book",
  libros: "books",
  leer: "read",
  lectura: "read",
  biblioteca: "library",
  casa: "house",
  hogar: "home",
  familia: "family",
  personas: "people",
  gente: "people",
  corazon: "heart",
  amor: "heart",
  salud: "health",
  hospital: "hospital",
  perro: "dog",
  gato: "cat",
  mascota: "pet",
  animal: "animal",
  comida: "food",
  cafe: "coffee",
  te: "tea",
  pan: "bread",
  cerveza: "beer",
  vino: "wine",
  restaurante: "restaurant",
  tienda: "shop",
  mercado: "market",
  compras: "shopping",
  trabajo: "work",
  oficina: "office",
  empresa: "business",
  reunion: "meeting",
  cita: "date",
  estudio: "school",
  escuela: "school",
  universidad: "university",
  musica: "music",
  cancion: "musical_note",
  pelicula: "movie",
  peliculas: "movies",
  serie: "tv",
  series: "tv",
  television: "tv",
  viajar: "travel",
  viaje: "airplane",
  avion: "airplane",
  coche: "car",
  auto: "car",
  carro: "car",
  bici: "bike",
  tren: "train",
  arte: "art",
  pintar: "paint",
  camara: "camera",
  foto: "camera",
  ordenador: "computer",
  codigo: "code",
  telefono: "phone",
  bombilla: "bulb",
  caja: "package",
  paquete: "package",
  herramientas: "tools",
  llave: "key",
  calendario: "calendar",
  reloj: "clock",
  alarma: "alarm_clock",
  dinero: "money",
  pago: "money",
  factura: "money",
  banco: "bank",
  alerta: "warning",
  aviso: "warning",
  peligro: "warning",
  estrella: "star",
  favorita: "star",
  hecho: "check",
  papel: "paper",
  higienico: "toilet",
  tijeras: "scissors",
  botella: "bottle",
  plato: "plate",
  cuchara: "spoon",
  tenedor: "fork",
  cuchillo: "knife",
  cama: "bed",
  arbol: "tree",
  flor: "flower",
  carta: "letter",
  regalo: "gift",
  fiesta: "party",
  cumpleanos: "birthday",
  bebe: "baby",
  pelo: "hair",
  camisa: "shirt",
  sombrero: "hat",
  paraguas: "umbrella",
  maleta: "luggage",
  barco: "boat",
  playa: "beach",
  montana: "mountain",
  jardin: "garden",
  medico: "doctor",
  farmacia: "pharmacy",
  dentista: "dentist",
  policia: "police",
  bombero: "firefighter",
  cocinero: "cook",
  profesor: "teacher",
  alumno: "student",
  examen: "exam",
  lapiz: "pencil",
  regla: "ruler",
  mochila: "backpack",
  paz: "peace",
  muerte: "death",
  enfermedad: "disease",
  fiebre: "fever",
  moco: "snot",
  herida: "wound",
  sangre: "blood",
  hueso: "bone",
  cerebro: "brain",
  musculo: "muscle",
  dedo: "finger",
  nariz: "nose",
  lengua: "tongue",
  diente: "tooth",
  dientes: "teeth",
  cuello: "neck",
  rodilla: "knee",
  barriga: "belly",
  pulgar: "thumb",
  indice: "index_finger",
  vena: "vein",
  pies: "feet",
  dedos: "fingers",
  fuego: "fire",
  ciudad: "city",
  bicicleta: "bike",
  pantalon: "pants",
  muneca: "wrist",
  munecas: "wrist",
  ceja: "eyebrow",
};
