/**
 * Spanish words that are not in the data.
 *
 * `emojilib` brings 15412 keywords in English and there is no Spanish edition:
 * "book" finds a book and "libro" finds nothing. This is the short table that
 * closes the gap for the words of this app, and it is short on purpose — it is
 * not a dictionary and it is not going to become one. The words that are missing
 * are found when somebody types them and gets nothing.
 *
 * The key is what the person types on a Spanish keyboard, and the value is what
 * the data brings. A key that is already English needs no alias and gets none.
 */
export const EMOJI_ALIASES: Record<string, string> = {
  libro: "book",
  libros: "books",
  leer: "read",
  lectura: "read",
  biblioteca: "library",
  casa: "house",
  hogar: "home",
  familia: "family",
  personas: "people",
  gente: "people",
  corazon: "heart",
  amor: "heart",
  salud: "health",
  hospital: "hospital",
  perro: "dog",
  gato: "cat",
  mascota: "pet",
  animal: "animal",
  comida: "food",
  cafe: "coffee",
  te: "tea",
  pan: "bread",
  cerveza: "beer",
  vino: "wine",
  restaurante: "restaurant",
  tienda: "shop",
  mercado: "market",
  compras: "shopping",
  trabajo: "work",
  oficina: "office",
  empresa: "business",
  reunion: "meeting",
  cita: "date",
  estudio: "school",
  escuela: "school",
  universidad: "university",
  musica: "music",
  cancion: "musical_note",
  pelicula: "movie",
  peliculas: "movies",
  serie: "tv",
  series: "tv",
  television: "tv",
  viajar: "travel",
  viaje: "airplane",
  avion: "airplane",
  coche: "car",
  auto: "car",
  carro: "car",
  bici: "bike",
  tren: "train",
  arte: "art",
  pintar: "paint",
  camara: "camera",
  foto: "camera",
  ordenador: "computer",
  codigo: "code",
  telefono: "phone",
  bombilla: "bulb",
  caja: "package",
  paquete: "package",
  herramientas: "tools",
  llave: "key",
  calendario: "calendar",
  reloj: "clock",
  alarma: "alarm_clock",
  dinero: "money",
  pago: "money",
  factura: "money",
  banco: "bank",
  alerta: "warning",
  aviso: "warning",
  peligro: "warning",
  estrella: "star",
  favorita: "star",
  hecho: "white_check_mark",
};
