/**
 * The catalogue, part three: MaterialCommunityIcons.
 *
 * Ionicons tops out at 421 glyphs with an outline variant and the catalogue was
 * using 418 of them, so the picker felt short no matter how many words were added.
 * `MaterialCommunityIcons` ships in the same `@expo/vector-icons` package -- no new
 * dependency, same root font loading, works on web -- with **7448 glyphs**.
 *
 * Same format as the rest: `clave glifo`, the Spanish word somebody types and the
 * English name of the glyph that draws it. Every entry below is checked against
 * the real `glyphMap` by `test/icons-material.test.ts`: a typo, a repeated key or
 * a repeated glyph all fail loudly instead of drawing a blank cell.
 *
 * One glyph, one key: the draft had fifty glyphs named twice (three `buzon`, four
 * `compass`), and each keeps a single Spanish word. The catalogue never holds the
 * same drawing twice -- that is the whole point of the deduplicated grid.
 */

/** `clave glifo`, grouped by the same eleven categories as everything else. */
export const MATERIAL_BY_CATEGORY: Record<string, readonly string[]> = {
  comida: [
    "manzana food-apple",
    "croissant_dulce food-croissant",
    "muslo food-drumstick",
    "perrito food-hot-dog",
    "filete food-steak",
    "comida_llevar food-takeout-box",
    "hamburguesa hamburger",
    "taco taco",
    "pan_rebanada bread-slice",
    "tarta_pisos cake-layered",
    "huevo_frito egg-fried",
    "huevo_pascua egg-easter",
    "pecera fishbowl",
    "cerezas fruit-cherries",
    "citricos fruit-citrus",
    "uvas fruit-grapes",
    "picante chili-hot",
    "chile chili-medium",
    "maiz corn",
    "puerro leek",
    "cacahuete peanut",
    "olla_vapor pot-steam",
    "olla_mezcla pot-mix",
    "bol_mezcla bowl-mix",
    "parrilla grill",
    "tetera_verdadera kettle-pour-over",
    "cafe_llevar coffee-to-go",
    "cafetera coffee-maker",
    "vaso_agua cup-water",
    "copa_vino glass-wine",
    "jarra glass-mug",
    "flauta glass-flute",
    "botella_vino bottle-wine",
    "botella_refresco bottle-soda",
    "tostadora toaster",
    "horno_tostador toaster-oven",
    "microondas microwave",
    "nevera_variante fridge-variant",
    "batidora blender",
    "hervidor kettle",
    "cuchillo knife",
    "cubiertos silverware-fork-knife",
    "cuchara_plata silverware-spoon",
    "gorro_cocinero chef-hat",
    "pretzel pretzel",
    "caramelo candy",
    "caramelo_no candy-off",
    "huevo_no egg-off",
    "vaso_no cup-off",
    "cafe_no coffee-off",
    "comida_no food-off",
    "muslo_no food-drumstick-off",
    "bol bowl",
    "champinon_no mushroom-off",
    "cacahuete_no peanut-off",
    "salchicha sausage",
    "setas mushroom",
  ],
  naturaleza: [
    "perro_lado dog-side",
    "perro_servicio dog-service",
    "pajaro bird",
    "pez fish",
    "conejo rabbit",
    "tortuga turtle",
    "caracol snail",
    "mariposa butterfly",
    "abeja bee",
    "arana spider",
    "pinguino penguin",
    "panda panda",
    "koala koala",
    "delfin dolphin",
    "tiburon shark",
    "foca seal",
    "unicornio unicorn",
    "huella paw",
    "hueso bone",
    "murcielago bat",
    "medusa jellyfish",
    "buho owl",
    "caballo horse",
    "cerdo pig",
    "vaca cow",
    "oveja sheep",
    "pato duck",
    "serpiente snake",
    "elefante elephant",
    "canguro kangaroo",
    "burro donkey",
  ],
  social: [
    "persona account",
    "persona_corazon account-heart",
    "persona_estrella account-star",
    "cara_bebe baby-face",
    "arbol_familiar family-tree",
    "cara_hombre face-man",
    "cara_mujer face-woman",
    "feliz emoticon-happy",
    "enfadado emoticon-angry",
    "llorando emoticon-cry",
    "enfermo emoticon-sick",
    "guay emoticon-cool",
    "diablo emoticon-devil",
    "beso emoticon-kiss",
    "ilusionado emoticon-excited",
    "ceño emoticon-frown",
    "confundido emoticon-confused",
    "muerto emoticon-dead",
    "corazon heart",
    "corazones heart-multiple",
    "mano_corazon hand-heart",
    "manos_rezo hands-pray",
    "apreton handshake",
    "charla chat",
    "camara_social camera",
    "globo_fiesta balloon",
    "bailarina dance-ballroom",
    "bailarina_mujer human-female-dance",
    "anillo ring",
  ],
  deporte: [
    "futbol soccer",
    "voleibol volleyball",
    "rugby rugby",
    "billar billiards",
    "guante_boxeo boxing-glove",
    "kitesurf kitesurfing",
    "snowboard snowboard",
    "monopatin skateboard",
    "mancuerna dumbbell",
    "podio podium",
    "silbato whistle",
    "diana target",
    "esgrima fencing",
    "cricket cricket",
    "badminton badminton",
    "ajedrez chess-knight",
    "cartas cards",
    "puzle puzzle",
    "remo rowing",
  ],
  trabajo: [
    "maletin briefcase",
    "oficina office-building",
    "escritorio desk",
    "lampara_escritorio desk-lamp",
    "impresora printer",
    "cuaderno_trabajo notebook",
    "boli pen",
    "clip paperclip",
    "documento file-document",
    "carpeta_trabajo folder",
    "calculadora_trabajo calculator",
    "grafico_lineas chart-line",
    "traje account-tie",
    "corbata tie",
    "cafe_oficina coffee",
    "banco bank",
    "tarjeta_credito credit-card",
    "altavoz_trabajo speaker",
    "pantalla monitor",
    "teclado_trabajo keyboard",
    "raton_trabajo mouse",
    "escaner scanner",
    "trituradora shredder",
    "flexo lamp",
    "papelera_oficina trash-can",
    "carpeta_colgante folder-open",
    "bandeja tray",
    "bandeja_entrada inbox",
    "firma_trabajo signature",
    "factura invoice",
    "euro currency-eur",
    "dolar currency-usd",
  ],
  hogar: [
    "sofa sofa",
    "cama bed",
    "caja_herramientas toolbox",
    "destornillador screwdriver",
    "escalera ladder",
    "pala shovel",
    "flor flower",
    "mando remote",
    "aire_acondicionado air-conditioner",
    "ventilador fan",
    "radiador radiator",
    "reciclaje recycle",
    "ducha shower",
    "banera bathtub",
    "inodoro toilet",
    "grifo faucet",
    "plancha iron",
    "cubo_fregar bucket",
    "armario wardrobe",
    "comoda dresser",
    "literas bunk-bed",
    "peluche teddy-bear",
    "libro_hogar book",
    "cesped grass",
    "valla fence",
    "puerta_jardin gate",
    "timbre doorbell",
    "toldo awning",
    "balcon balcony",
    "fuente fountain",
    "mesa_jardin table",
    "luces_navidad string-lights",
    "arbol_navidad pine-tree",
  ],
  tecnologia: [
    "bateria battery",
    "senal signal",
    "antena antenna",
    "chip chip",
    "procesador cpu-64-bit",
    "robot robot",
    "base_datos database",
    "bicho bug",
    "reloj_pulsera watch",
    "webcam webcam",
    "router router-wireless",
    "satelite satellite",
    "radar radar",
    "dron quadcopter",
    "realidad_virtual virtual-reality",
    "pantalla_tv television",
    "pantalla_proyeccion projector-screen",
    "bombilla_inteligente lightbulb",
    "enchufe_inteligente power-plug",
    "interruptor light-switch",
    "termostato thermostat",
    "camara_seguridad cctv",
    "alarma_seguridad alarm",
    "sensor motion-sensor",
    "puerta_inteligente door",
    "cerradura_inteligente lock",
    "volante steering",
    "interruptor_palanca toggle-switch",
    "radio_tech radio",
    "telefono_fijo phone-classic",
    "fax fax",
    "bateria_cargando battery-charging",
    "placa_solar solar-panel",
    "molino wind-turbine",
    "disco_duro harddisk",
    "usb_memoria usb-flash-drive",
    "tarjeta_sd sd",
    "cd disc",
    "casete cassette",
    "altavoz_bluetooth speaker-bluetooth",
    "barra_sonido soundbar",
    "auriculares_inalambricos headphones",
    "cascos headset",
    "amplificador amplifier",
    "ecualizador equalizer",
    "teclado_musical piano",
    "trompeta trumpet",
    "saxofon saxophone",
    "violin violin",
    "metronomo metronome",
    "nota_musical music-note",
    "microfono_condensador microphone-variant",
  ],
  comunicacion: [
    "mensaje_texto message-text",
    "chat_procesando chat-processing",
    "telefono phone",
    "colgar phone-hangup",
    "video video",
    "buzon_voz voicemail",
    "campana_sonando bell-ring",
    "altavoz_anuncio bullhorn",
    "rss rss",
    "arroba at",
    "web web",
    "tierra earth",
    "caja_paquete box",
    "bici_mensajero bike",
    "almacen warehouse",
    "carretilla forklift",
    "pegatina sticker",
    "brujula compass",
    "semáforo traffic-light",
    "stop_comunicacion stop",
    "autopista highway",
    "carretera road",
    "puente bridge",
    "tunel tunnel",
    "aparcamiento parking",
    "gasolinera gas-station",
    "lavadero car-wash",
    "monedero purse",
    "ancla anchor",
    "gafas_sol sunglasses",
    "mapa_montana map",
    "hornillo stove",
    "cazo_montana pot",
  ],
  general: [
    "casa home",
    "puntos dots-vertical",
    "deshacer undo",
    "sincronizar sync",
    "subir upload",
    "borrar delete",
    "ordenar sort",
    "ojo eye",
    "ojo_tachado eye-off",
    "candado_abierto lock-open",
    "bandera flag",
    "calendario calendar",
    "reloj clock",
    "navegacion navigation",
    "cesta basket",
    "camion truck",
    "codigo_barras barcode",
    "entrada ticket",
    "descuento percent",
    "rebajas sale",
    "regla ruler",
    "chincheta pin",
    "paraguas umbrella",
    "tienda_campana tent",
    "tranvia tram",
    "andar walk",
    "engranaje cog",
    "tuerca nut",
    "clavo nail",
    "alicate pliers",
    "escuadra square",
    "lapiz_obra pencil",
    "pincel brush",
    "paleta_pintor palette",
    "foto image",
    "album album",
    "microfono microphone",
    "consola gamepad",
    "libros bookshelf",
    "periodico newspaper",
    "paquete_correo package",
    "buzon mailbox",
    "ola wave",
    "palomitas popcorn",
    "pavo turkey",
    "milano kite",
  ],
};

/**
 * Keys whose glyph has no outline variant of its own.
 *
 * Material names its outline versions as separate glyphs (`beer` and
 * `beer-outline` are two names), and most simply have none. Those draw the same
 * picture in both styles rather than hiding: a drawing that exists in one version
 * is shown in both. `vectorGlyph` reads this set; the picker never does.
 */
export const MATERIAL_FILL_ONLY: ReadonlySet<string> = new Set([
  "abeja",
  "aire_acondicionado",
  "ajedrez",
  "alarma_seguridad",
  "album",
  "alicate",
  "almacen",
  "altavoz_bluetooth",
  "altavoz_trabajo",
  "amplificador",
  "ancla",
  "andar",
  "anillo",
  "antena",
  "aparcamiento",
  "arbol_familiar",
  "arbol_navidad",
  "arroba",
  "auriculares_inalambricos",
  "autopista",
  "badminton",
  "bailarina",
  "bailarina_mujer",
  "balcon",
  "bandeja",
  "barra_sonido",
  "bici_mensajero",
  "billar",
  "boli",
  "buho",
  "burro",
  "buzon_voz",
  "caballo",
  "caja_paquete",
  "calculadora_trabajo",
  "camara_seguridad",
  "canguro",
  "caracol",
  "carretera",
  "carretilla",
  "cascos",
  "casete",
  "cd",
  "cerdo",
  "cerezas",
  "cesped",
  "chip",
  "citricos",
  "clavo",
  "clip",
  "codigo_barras",
  "conejo",
  "copa_vino",
  "corbata",
  "cricket",
  "croissant_dulce",
  "cubiertos",
  "cuchara_plata",
  "cuchillo",
  "delfin",
  "deshacer",
  "destornillador",
  "diana",
  "disco_duro",
  "dolar",
  "dron",
  "ducha",
  "elefante",
  "escalera",
  "escaner",
  "escritorio",
  "esgrima",
  "euro",
  "fax",
  "filete",
  "firma_trabajo",
  "flauta",
  "foca",
  "fuente",
  "futbol",
  "gafas_sol",
  "globo_fiesta",
  "gorro_cocinero",
  "grafico_lineas",
  "grifo",
  "guante_boxeo",
  "hamburguesa",
  "hornillo",
  "horno_tostador",
  "hueso",
  "huevo_frito",
  "huevo_pascua",
  "inodoro",
  "interruptor",
  "jarra",
  "kitesurf",
  "koala",
  "lampara_escritorio",
  "lavadero",
  "libros",
  "luces_navidad",
  "maiz",
  "mancuerna",
  "mando",
  "manos_rezo",
  "mesa_jardin",
  "metronomo",
  "microfono_condensador",
  "microondas",
  "molino",
  "monopatin",
  "murcielago",
  "ola",
  "ordenar",
  "oveja",
  "pajaro",
  "pala",
  "palomitas",
  "panda",
  "pantalla",
  "pantalla_tv",
  "paquete_correo",
  "pato",
  "pavo",
  "peluche",
  "periodico",
  "perrito",
  "perro_lado",
  "perro_servicio",
  "pez",
  "pinguino",
  "placa_solar",
  "podio",
  "pretzel",
  "procesador",
  "puente",
  "puerro",
  "puerta_inteligente",
  "puerta_jardin",
  "puntos",
  "radar",
  "radiador",
  "radio_tech",
  "realidad_virtual",
  "reciclaje",
  "regla",
  "reloj_pulsera",
  "remo",
  "router",
  "rss",
  "rugby",
  "salchicha",
  "satelite",
  "saxofon",
  "senal",
  "sensor",
  "serpiente",
  "sincronizar",
  "snowboard",
  "stop_comunicacion",
  "taco",
  "tarjeta_sd",
  "tarta_pisos",
  "teclado_musical",
  "telefono_fijo",
  "termostato",
  "tetera_verdadera",
  "tiburon",
  "tienda_campana",
  "tierra",
  "timbre",
  "tortuga",
  "tostadora",
  "tranvia",
  "trituradora",
  "trompeta",
  "tuerca",
  "unicornio",
  "vaca",
  "valla",
  "vaso_agua",
  "ventilador",
  "violin",
  "volante",
  "voleibol",
  "web",
  "webcam",
]);

/**
 * Words that need spelling out: the grid reads them and the search shows them.
 * Only the ones the key cannot spell on its own.
 */
export const MATERIAL_LABELS: Record<string, string> = {
  comida_no: "Sin comida",
  muslo_no: "Sin muslo",
  caramelo_no: "Sin caramelo",
  huevo_no: "Sin huevo",
  vaso_no: "Sin vaso",
  cafe_no: "Sin café",
  comida_llevar: "Comida para llevar",
  gorro_cocinero: "Gorro de cocinero",
  olla_vapor: "Olla al vapor",
  olla_mezcla: "Olla de mezcla",
  bol_mezcla: "Bol de mezcla",
  tetera_verdadera: "Tetera de goteo",
  vaso_agua: "Vaso de agua",
  copa_vino: "Copa de vino",
  jarra: "Jarra",
  flauta: "Copa flauta",
  botella_vino: "Botella de vino",
  botella_refresco: "Botella de refresco",
  horno_tostador: "Horno tostador",
  nevera_variante: "Nevera",
  cubiertos: "Cubiertos",
  cuchara_plata: "Cuchara",
  huevo_frito: "Huevo frito",
  huevo_pascua: "Huevo de pascua",
  perrito: "Perrito caliente",
  filete: "Filete",
  croissant_dulce: "Cruasán",
  pan_rebanada: "Rebanada de pan",
  conejo: "Conejo",
  cerdo: "Cerdo",
  cerezas: "Cerezas",
  citricos: "Cítricos",
};

/**
 * Words that should find a drawing they are not called.
 * The key is a drawing, the value the words somebody reaches for.
 */
export const MATERIAL_KEYWORDS: Record<string, string> = {
  manzana: "apple|fruta",
  hamburguesa: "burger",
  palomitas: "cine|peli",
  conejo: "mascota|pascua",
  tortuga: "reptil|lenta",
  pajaro: "ave|volar",
  pez: "pescado|acuario",
  persona: "usuario|perfil|cuenta",
  corazon: "amor|favorito|like",
  futbol: "balon|deporte|pelota",
  maletin: "trabajo|negocios|oficina",
  oficina: "trabajo|empresa|edificio",
  impresora: "imprimir|oficina",
  calendario: "fecha|agenda|cita",
  reloj: "hora|tiempo",
  banco: "dinero|ahorros",
  tarjeta_credito: "pagar|banco|visa",
  sofa: "sillon|descanso|tv",
  cama: "dormir|descanso|noche",
  mando: "tv|control",
  ducha: "bano|agua",
  inodoro: "bano|wc|retrete",
  bateria: "pila|carga",
  robot: "ia|automatico",
  microfono: "voz|grabar|audio",
  reloj_pulsera: "hora|wearable",
  bici_mensajero: "reparto",
  brujula: "norte|orientacion",
  flor: "planta|primavera|jardin",
  casa: "hogar|inicio",
  subir: "upload|cargar",
  bandera: "pais|meta",
  codigo_barras: "escanear|producto",
  entrada: "ticket|boleto|acceso",
  descuento: "oferta|rebaja|tanto_porciento",
};
