/**
 * The icons a row can have.
 *
 * The key is the word a person would use for the thing — "pan", "pilas",
 * "ferreteria" — and that is the same word they type in the search. So the
 * label is the key with a capital letter, and only the words that are wrong on
 * their own need a dictionary entry. Four hundred strings of "Pan" in a file
 * that has to be translated twice is four hundred chances to mistype one, and a
 * mistyped label is an icon nobody can find because nobody can spell what they
 * see.
 *
 * They live in the contract and not in the app because the server refuses a key
 * nobody can draw: an item that arrives with an icon this build has never heard
 * of would show a blank space where the picture should be, and the blank space
 * is on somebody else's list, not on the screen of the person who wrote it.
 */
export const ITEM_ICONS = [
  "pan",
  "leche",
  "agua",
  "cafe",
  "te",
  "cerveza",
  "vino",
  "refresco",
  "zumo",
  "fruta",
  "verdura",
  "queso",
  "huevo",
  "carne",
  "pollo",
  "pescado",
  "marisco",
  "arroz",
  "pasta",
  "chocolate",
  "dulces",
  "comida_bebe",
  "detergente",
  "jabon",
  "champu",
  "pasta_dientes",
  "papel",
  "toallitas",
  "limpieza",
  "bolsa",
  "cubierto",
  "bombilla",
  "pila",
  "cargador",
  "herramienta",
  "tornillo",
  "cinta",
  "pegamento",
  "ropa",
  "camiseta",
  "pantalon",
  "zapato",
  "bota",
  "abrigo",
  "calcetin",
  "ropa_interior",
  "bolso",
  "cinturon",
  "pastilla",
  "medicina",
  "tirita",
  "crema",
  "vitaminas",
  "termometro",
  "bebe",
  "panal",
  "chupete",
  "leche_materna",
  "juguete",
  "parque",
  "lampara",
  "manta",
  "almohada",
  "sabana",
  "toalla",
  "cortina",
  "alfombra",
  "mesa",
  "silla",
  "vaso",
  "plato",
  "cuchara",
  "tenedor",
  "olla",
  "sarten",
  "congelador",
  "lavadora",
  "aspiradora",
  "coche",
  "gasolina",
  "aceite",
  "neumatico",
  "bateria_coche",
  "tarjeta_azul",
  "billete",
  "hotel",
  "maleta",
  "vuelo",
  "tren",
  "bus",
  "taxi",
  "bici",
  "casco",
  "perro",
  "gato",
  "comida_perro",
  "transportin",
  "veterinario",
  "cuaderno",
  "libro",
  "boligrafo",
  "lapiz",
  "goma",
  "mochila",
  "carpeta",
  "calculadora",
  "rotulador",
  "tijeras",
  "usb",
  "balon",
  "tenis",
  "gafas",
  "gorro",
  "bufanda",
  "botas",
  "bicicleta",
  "natacion",
  "gimnasio",
  "dvd",
  "juego",
  "musica",
  "auriculares",
  "regalo",
  "caja",
  "paquete",
  "teclado",
  "raton",
  "monitor",
  "wifi",
  "bombilla_led",
  "iluminar",
] as const;
export type ItemIcon = (typeof ITEM_ICONS)[number];

/**
 * The groups the picker shows, in the order it shows them.
 *
 * Nine hundred icons in one grid is a wall, and a wall is a list you scroll past
 * instead of read. The groups are the ones a shopping list is actually made of,
 * and every icon is in exactly one of them: an icon in none of them is an icon
 * nobody finds, and an icon in two of them is an icon that appears twice.
 */
export const ITEM_ICON_CATEGORIES = [
  "comida",
  "limpieza",
  "casa",
  "ropa",
  "salud",
  "bebes",
  "fuera",
  "mascotas",
  "estudio",
  "deporte",
] as const;
export type ItemIconCategory = (typeof ITEM_ICON_CATEGORIES)[number];

/** Which group each icon is in, and the same list spelled out as a map. */
export const ITEM_ICON_GROUP: Record<ItemIcon, ItemIconCategory> = {
  pan: "comida",
  leche: "comida",
  agua: "comida",
  cafe: "comida",
  te: "comida",
  cerveza: "comida",
  vino: "comida",
  refresco: "comida",
  zumo: "comida",
  fruta: "comida",
  verdura: "comida",
  queso: "comida",
  huevo: "comida",
  carne: "comida",
  pollo: "comida",
  pescado: "comida",
  marisco: "comida",
  arroz: "comida",
  pasta: "comida",
  chocolate: "comida",
  dulces: "comida",
  comida_bebe: "comida",
  detergente: "limpieza",
  jabon: "limpieza",
  champu: "limpieza",
  pasta_dientes: "limpieza",
  papel: "limpieza",
  toallitas: "limpieza",
  limpieza: "limpieza",
  bolsa: "limpieza",
  cubierto: "limpieza",
  bombilla: "casa",
  pila: "casa",
  cargador: "casa",
  herramienta: "casa",
  tornillo: "casa",
  cinta: "casa",
  pegamento: "casa",
  ropa: "ropa",
  camiseta: "ropa",
  pantalon: "ropa",
  zapato: "ropa",
  bota: "ropa",
  abrigo: "ropa",
  calcetin: "ropa",
  ropa_interior: "ropa",
  bolso: "ropa",
  cinturon: "ropa",
  pastilla: "salud",
  medicina: "salud",
  tirita: "salud",
  crema: "salud",
  vitaminas: "salud",
  termometro: "salud",
  bebe: "bebes",
  panal: "bebes",
  chupete: "bebes",
  leche_materna: "bebes",
  juguete: "bebes",
  parque: "bebes",
  lampara: "casa",
  manta: "casa",
  almohada: "casa",
  sabana: "casa",
  toalla: "casa",
  cortina: "casa",
  alfombra: "casa",
  mesa: "casa",
  silla: "casa",
  vaso: "casa",
  plato: "casa",
  cuchara: "casa",
  tenedor: "casa",
  olla: "casa",
  sarten: "casa",
  congelador: "casa",
  lavadora: "limpieza",
  aspiradora: "limpieza",
  coche: "fuera",
  gasolina: "fuera",
  aceite: "fuera",
  neumatico: "fuera",
  bateria_coche: "fuera",
  tarjeta_azul: "fuera",
  billete: "fuera",
  hotel: "fuera",
  maleta: "fuera",
  vuelo: "fuera",
  tren: "fuera",
  bus: "fuera",
  taxi: "fuera",
  bici: "fuera",
  casco: "fuera",
  perro: "mascotas",
  gato: "mascotas",
  comida_perro: "mascotas",
  transportin: "mascotas",
  veterinario: "salud",
  cuaderno: "estudio",
  libro: "estudio",
  boligrafo: "estudio",
  lapiz: "estudio",
  goma: "estudio",
  mochila: "fuera",
  carpeta: "estudio",
  calculadora: "estudio",
  rotulador: "estudio",
  tijeras: "estudio",
  usb: "estudio",
  balon: "deporte",
  tenis: "deporte",
  gafas: "deporte",
  gorro: "ropa",
  bufanda: "ropa",
  botas: "ropa",
  bicicleta: "fuera",
  natacion: "deporte",
  gimnasio: "deporte",
  dvd: "deporte",
  juego: "deporte",
  musica: "deporte",
  auriculares: "estudio",
  regalo: "casa",
  caja: "casa",
  paquete: "casa",
  teclado: "estudio",
  raton: "estudio",
  monitor: "estudio",
  wifi: "estudio",
  bombilla_led: "casa",
  iluminar: "casa",
};

/**
 * The colours an icon can be drawn in.
 *
 * Ten, and not a colour picker. An icon is a small shape on a busy list, and a
 * colour on it has to be one you can read at that size from a thumb's distance:
 * two reds look like one red, and a pale yellow on white is not a colour, it is
 * nothing. Ten is as many as stay apart at 18 points.
 */
export const ITEM_ICON_COLORS = [
  "neutral",
  "accent",
  "green",
  "olive",
  "amber",
  "orange",
  "red",
  "rose",
  "purple",
  "blue",
  "teal",
  "brown",
] as const;
export type ItemIconColor = (typeof ITEM_ICON_COLORS)[number];

/** Whether a string is one of the icons this build knows how to draw. */
export function isItemIcon(value: unknown): value is ItemIcon {
  return typeof value === "string" && (ITEM_ICONS as readonly string[]).includes(value);
}
